In [1]:
import numpy as np
np
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [2]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [4]:
np.arange(2, 9)

array([2, 3, 4, 5, 6, 7, 8])

In [5]:
pd.__version__

NameError: name 'pd' is not defined

In [6]:
import pandas as pd
pd
pd.__version__

'2.3.2'